package iso8583

// Message defines the structure of ISO 8583 messages
type Message struct {
	MTI          string         // 4 digit numeric number
	Bitmap       []string       // primary bitmap
	DataElements map[int]string // data elements on fields
}

func (m Message) String() string {
	return ""
}

// Field defines the properties of ISO 8583 data elements
type Field struct {
	Field    int
	Format   string
	Length   int
	Variable int // 0 -> fixed, 1,2,3 - field length indicators (2-LLVAR, 3-LLLVAR)
	Usage    string
}

// Fields are all ISO 8583 data elements
var Fields = map[int]Field{
	1:   {Field: 1, Format: "b", Length: 64, Variable: 0, Usage: "Bit map (b 128 if secondary is present and b 192 if tertiary is present)"},
	2:   {Field: 2, Format: "n", Length: 19, Variable: 2, Usage: "Primary account number (PAN)"},
	3:   {Field: 3, Format: "n", Length: 6, Variable: 0, Usage: "Processing code"},
	4:   {Field: 4, Format: "n", Length: 12, Variable: 0, Usage: "Amount, transaction"},
	5:   {Field: 5, Format: "n", Length: 12, Variable: 0, Usage: "Amount, settlement"},
	6:   {Field: 6, Format: "n", Length: 12, Variable: 0, Usage: "Amount, cardholder billing"},
	7:   {Field: 7, Format: "n", Length: 10, Variable: 0, Usage: "Transmission date & time"},
	8:   {Field: 8, Format: "n", Length: 8, Variable: 0, Usage: "Amount, cardholder billing fee"},
	9:   {Field: 9, Format: "n", Length: 8, Variable: 0, Usage: "Conversion rate, settlement"},
	10:  {Field: 10, Format: "n", Length: 8, Variable: 0, Usage: "Conversion rate, cardholder billing"},
	11:  {Field: 11, Format: "n", Length: 6, Variable: 0, Usage: "System trace audit number (STAN)"},
	12:  {Field: 12, Format: "n", Length: 6, Variable: 0, Usage: "Time, local transaction (hhmmss)"},
	13:  {Field: 13, Format: "n", Length: 4, Variable: 0, Usage: "Date, local transaction (MMDD)"},
	14:  {Field: 14, Format: "n", Length: 4, Variable: 0, Usage: "Date, expiration"},
	15:  {Field: 15, Format: "n", Length: 4, Variable: 0, Usage: "Date, settlement"},
	16:  {Field: 16, Format: "n", Length: 4, Variable: 0, Usage: "Date, conversion"},
	17:  {Field: 17, Format: "n", Length: 4, Variable: 0, Usage: "Date, capture"},
	18:  {Field: 18, Format: "n", Length: 4, Variable: 0, Usage: "Merchant type"},
	19:  {Field: 19, Format: "n", Length: 3, Variable: 0, Usage: "Acquiring institution country code"},
	20:  {Field: 20, Format: "n", Length: 3, Variable: 0, Usage: "PAN extended, country code"},
	21:  {Field: 21, Format: "n", Length: 3, Variable: 0, Usage: "Forwarding institution. country code"},
	22:  {Field: 22, Format: "n", Length: 3, Variable: 0, Usage: "Point of service entry mode"},
	23:  {Field: 23, Format: "n", Length: 3, Variable: 0, Usage: "Application PAN sequence number"},
	24:  {Field: 24, Format: "n", Length: 3, Variable: 0, Usage: "Function code (ISO 8583:1993)/Network International identifier (NII)"},
	25:  {Field: 25, Format: "n", Length: 2, Variable: 0, Usage: "Point of service condition code"},
	26:  {Field: 26, Format: "n", Length: 2, Variable: 0, Usage: "Point of service capture code"},
	27:  {Field: 27, Format: "n", Length: 1, Variable: 0, Usage: "Authorizing identification response length"},
	28:  {Field: 28, Format: "x+n", Length: 8, Variable: 0, Usage: "Amount, transaction fee"},
	29:  {Field: 29, Format: "x+n", Length: 8, Variable: 0, Usage: "Amount, settlement fee"},
	30:  {Field: 30, Format: "x+n", Length: 8, Variable: 0, Usage: "Amount, transaction processing fee"},
	31:  {Field: 31, Format: "x+n", Length: 8, Variable: 0, Usage: "Amount, settlement processing fee"},
	32:  {Field: 32, Format: "n", Length: 11, Variable: 2, Usage: "Acquiring institution identification code"},
	33:  {Field: 33, Format: "n", Length: 11, Variable: 2, Usage: "Forwarding institution identification code"},
	34:  {Field: 34, Format: "ns", Length: 28, Variable: 2, Usage: "Primary account number, extended"},
	35:  {Field: 35, Format: "z", Length: 37, Variable: 2, Usage: "Track 2 data"},
	36:  {Field: 36, Format: "n", Length: 104, Variable: 3, Usage: "Track 3 data"},
	37:  {Field: 37, Format: "an", Length: 12, Variable: 0, Usage: "Retrieval reference number"},
	38:  {Field: 38, Format: "an", Length: 6, Variable: 0, Usage: "Authorization identification response"},
	39:  {Field: 39, Format: "an", Length: 2, Variable: 0, Usage: "Response code"},
	40:  {Field: 40, Format: "an", Length: 3, Variable: 0, Usage: "Service restriction code"},
	41:  {Field: 41, Format: "ans", Length: 8, Variable: 0, Usage: "Card acceptor terminal identification"},
	42:  {Field: 42, Format: "ans", Length: 15, Variable: 0, Usage: "Card acceptor identification code"},
	43:  {Field: 43, Format: "ans", Length: 40, Variable: 0, Usage: "Card acceptor name/location (1-23 address 24-36 city 37-38 state 39-40 country)"},
	44:  {Field: 44, Format: "an", Length: 25, Variable: 2, Usage: "Additional response data"},
	45:  {Field: 45, Format: "an", Length: 76, Variable: 2, Usage: "Track 1 data"},
	46:  {Field: 46, Format: "an", Length: 999, Variable: 3, Usage: "Additional data - ISO"},
	47:  {Field: 47, Format: "an", Length: 999, Variable: 3, Usage: "Additional data - national"},
	48:  {Field: 48, Format: "an", Length: 999, Variable: 3, Usage: "Additional data - private"},
	49:  {Field: 49, Format: "a", Length: 3, Variable: 0, Usage: "Currency code, transaction"},
	50:  {Field: 50, Format: "a", Length: 3, Variable: 0, Usage: "Currency code, settlement"},
	51:  {Field: 51, Format: "a", Length: 3, Variable: 0, Usage: "Currency code, cardholder billing"},
	52:  {Field: 52, Format: "b", Length: 64, Variable: 0, Usage: " data"},
	53:  {Field: 53, Format: "n", Length: 16, Variable: 0, Usage: "Security related control information"},
	54:  {Field: 54, Format: "an", Length: 120, Variable: 3, Usage: "Additional amounts"},
	55:  {Field: 55, Format: "ans", Length: 999, Variable: 3, Usage: "ICC Data - EMV having multiple tags"},
	56:  {Field: 56, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved ISO"},
	57:  {Field: 57, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved national"},
	58:  {Field: 58, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved national"},
	59:  {Field: 59, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved national"},
	60:  {Field: 60, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved national"},
	61:  {Field: 61, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved private"},
	62:  {Field: 62, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved private"},
	63:  {Field: 63, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved private"},
	64:  {Field: 64, Format: "b", Length: 16, Variable: 0, Usage: "Message authentication code (MAC)"},
	65:  {Field: 65, Format: "b", Length: 1, Variable: 0, Usage: "Bitmap, extended"},
	66:  {Field: 66, Format: "n", Length: 1, Variable: 0, Usage: "Settlement code"},
	67:  {Field: 67, Format: "n", Length: 2, Variable: 0, Usage: "Extended payment code"},
	68:  {Field: 68, Format: "n", Length: 3, Variable: 0, Usage: "Receiving institution country code"},
	69:  {Field: 69, Format: "n", Length: 3, Variable: 0, Usage: "Settlement institution country code"},
	70:  {Field: 70, Format: "n", Length: 3, Variable: 0, Usage: "Network management information code"},
	71:  {Field: 71, Format: "n", Length: 4, Variable: 0, Usage: "Message number"},
	72:  {Field: 72, Format: "n", Length: 4, Variable: 0, Usage: "Message number, last"},
	73:  {Field: 73, Format: "n", Length: 6, Variable: 0, Usage: "Date, action (YYMMDD)"},
	74:  {Field: 74, Format: "n", Length: 10, Variable: 0, Usage: "Credits, number"},
	75:  {Field: 75, Format: "n", Length: 10, Variable: 0, Usage: "Credits, reversal number"},
	76:  {Field: 76, Format: "n", Length: 10, Variable: 0, Usage: "Debits, number"},
	77:  {Field: 77, Format: "n", Length: 10, Variable: 0, Usage: "Debits, reversal number"},
	78:  {Field: 78, Format: "n", Length: 10, Variable: 0, Usage: "Transfer number"},
	79:  {Field: 79, Format: "n", Length: 10, Variable: 0, Usage: "Transfer, reversal number"},
	80:  {Field: 80, Format: "n", Length: 10, Variable: 0, Usage: "Inquiries number"},
	81:  {Field: 81, Format: "n", Length: 10, Variable: 0, Usage: "Authorizations, number"},
	82:  {Field: 82, Format: "n", Length: 12, Variable: 0, Usage: "Credits, processing fee amount"},
	83:  {Field: 83, Format: "n", Length: 12, Variable: 0, Usage: "Credits, transaction fee amount"},
	84:  {Field: 84, Format: "n", Length: 12, Variable: 0, Usage: "Debits, processing fee amount"},
	85:  {Field: 85, Format: "n", Length: 12, Variable: 0, Usage: "Debits, transaction fee amount"},
	86:  {Field: 86, Format: "n", Length: 16, Variable: 0, Usage: "Credits, amount"},
	87:  {Field: 87, Format: "n", Length: 16, Variable: 0, Usage: "Credits, reversal amount"},
	88:  {Field: 88, Format: "n", Length: 16, Variable: 0, Usage: "Debits, amount"},
	89:  {Field: 89, Format: "n", Length: 16, Variable: 0, Usage: "Debits, reversal amount"},
	90:  {Field: 90, Format: "n", Length: 42, Variable: 0, Usage: "Original data elements"},
	91:  {Field: 91, Format: "an", Length: 1, Variable: 0, Usage: "File update code"},
	92:  {Field: 92, Format: "an", Length: 2, Variable: 0, Usage: "File security code"},
	93:  {Field: 93, Format: "an", Length: 5, Variable: 0, Usage: "Response indicator"},
	94:  {Field: 94, Format: "an", Length: 7, Variable: 0, Usage: "Service indicator"},
	95:  {Field: 95, Format: "an", Length: 42, Variable: 0, Usage: "Replacement amounts"},
	96:  {Field: 96, Format: "b", Length: 64, Variable: 0, Usage: "Message security code"},
	97:  {Field: 97, Format: "x+n", Length: 16, Variable: 0, Usage: "Amount, net settlement"},
	98:  {Field: 98, Format: "ans", Length: 25, Variable: 0, Usage: "Payee"},
	99:  {Field: 99, Format: "n", Length: 11, Variable: 2, Usage: "Settlement institution identification code"},
	100: {Field: 100, Format: "n", Length: 11, Variable: 2, Usage: "Receiving institution identification code"},
	101: {Field: 101, Format: "ans", Length: 17, Variable: 2, Usage: "File name"},
	102: {Field: 102, Format: "ans", Length: 28, Variable: 2, Usage: "Account identification 1"},
	103: {Field: 103, Format: "ans", Length: 28, Variable: 2, Usage: "Account identification 2"},
	104: {Field: 104, Format: "ans", Length: 100, Variable: 3, Usage: "Transaction description"},
	105: {Field: 105, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for ISO use"},
	106: {Field: 106, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for ISO use"},
	107: {Field: 107, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for ISO use"},
	108: {Field: 108, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for ISO use"},
	109: {Field: 109, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for ISO use"},
	110: {Field: 110, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for ISO use"},
	111: {Field: 111, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for ISO use"},
	112: {Field: 112, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for national use"},
	113: {Field: 113, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for national use"},
	114: {Field: 114, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for national use"},
	115: {Field: 115, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for national use"},
	116: {Field: 116, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for national use"},
	117: {Field: 117, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for national use"},
	118: {Field: 118, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for national use"},
	119: {Field: 119, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for national use"},
	120: {Field: 120, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for private use"},
	121: {Field: 121, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for private use"},
	122: {Field: 122, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for private use"},
	123: {Field: 123, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for private use"},
	124: {Field: 124, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for private use"},
	125: {Field: 125, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for private use"},
	126: {Field: 126, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for private use"},
	127: {Field: 127, Format: "ans", Length: 999, Variable: 3, Usage: "Reserved for private use"},
	128: {Field: 128, Format: "b", Length: 64, Variable: 0, Usage: "Message authentication code"},
}
